/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import control.DepensesController;
import control.FinanceController;
import dialog.DialogDepensesWindow;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.*;
import model.*;

/**
 *
 * @author mac
 */
public class DepensesWindow extends javax.swing.JFrame {
    
    private DialogDepensesWindow dialog;
    private FinanceController financeControl;
    private DefaultListModel<String> pastExpensesModel = new DefaultListModel<>();
    private DefaultListModel<String> upcomingExpensesModel = new DefaultListModel<>();

    /**
     * Creates new form DepensesWindow
     */
    public DepensesWindow(FinanceController financeControl) {
        this.financeControl = financeControl;
        initComponents();
        
        dialog = new DialogDepensesWindow(this);
       
        pastExpensesModel = new DefaultListModel<>();
        upcomingExpensesModel = new DefaultListModel<>();
        
        depensesList.setModel(pastExpensesModel);
        avenirList.setModel(upcomingExpensesModel);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setDialogue(DialogDepensesWindow dialog) {
        this.dialog = dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moisLabel = new javax.swing.JLabel();
        pastDepensesPanel = new javax.swing.JPanel();
        depensesLabel = new javax.swing.JLabel();
        depensesSeparator = new javax.swing.JSeparator();
        depensesScrollPane = new javax.swing.JScrollPane();
        depensesList = new javax.swing.JList<>();
        avenirDepensesPanel = new javax.swing.JPanel();
        avenirLabel = new javax.swing.JLabel();
        avenirSeparator = new javax.swing.JSeparator();
        avenirScrollPane = new javax.swing.JScrollPane();
        avenirList = new javax.swing.JList<>();
        totalLabel = new javax.swing.JLabel();
        deleteDepenseButton = new javax.swing.JButton();
        ajouterDepenseButton = new javax.swing.JButton();
        modifierDepenseButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moisLabel.setFont(new java.awt.Font("Baskerville", 0, 36)); // NOI18N
        moisLabel.setText("Mois");
        moisLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        moisLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pastDepensesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        depensesLabel.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        depensesLabel.setText("Depenses");
        depensesLabel.setToolTipText("");

        depensesScrollPane.setViewportView(depensesList);

        javax.swing.GroupLayout pastDepensesPanelLayout = new javax.swing.GroupLayout(pastDepensesPanel);
        pastDepensesPanel.setLayout(pastDepensesPanelLayout);
        pastDepensesPanelLayout.setHorizontalGroup(
            pastDepensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pastDepensesPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(depensesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pastDepensesPanelLayout.createSequentialGroup()
                .addComponent(depensesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depensesSeparator))
        );
        pastDepensesPanelLayout.setVerticalGroup(
            pastDepensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pastDepensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depensesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pastDepensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depensesSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depensesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        avenirDepensesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        avenirLabel.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        avenirLabel.setText("A venir");

        avenirList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        avenirScrollPane.setViewportView(avenirList);

        javax.swing.GroupLayout avenirDepensesPanelLayout = new javax.swing.GroupLayout(avenirDepensesPanel);
        avenirDepensesPanel.setLayout(avenirDepensesPanelLayout);
        avenirDepensesPanelLayout.setHorizontalGroup(
            avenirDepensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avenirDepensesPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(avenirLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avenirDepensesPanelLayout.createSequentialGroup()
                .addComponent(avenirScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avenirSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        avenirDepensesPanelLayout.setVerticalGroup(
            avenirDepensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avenirDepensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avenirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(avenirDepensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avenirSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avenirScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalLabel.setFont(new java.awt.Font("Heiti TC", 0, 18)); // NOI18N
        totalLabel.setText("Total: 500€");

        deleteDepenseButton.setText("-");
        deleteDepenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDepenseButtonActionPerformed(evt);
            }
        });

        ajouterDepenseButton.setText("+");
        ajouterDepenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterDepenseButtonActionPerformed(evt);
            }
        });

        modifierDepenseButton.setText("Modifier");
        modifierDepenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierDepenseButtonActionPerformed(evt);
            }
        });

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(totalLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backButton)
                                        .addGap(141, 141, 141)
                                        .addComponent(moisLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pastDepensesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(avenirDepensesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modifierDepenseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteDepenseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajouterDepenseButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moisLabel)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(totalLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pastDepensesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avenirDepensesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterDepenseButton)
                    .addComponent(deleteDepenseButton)
                    .addComponent(modifierDepenseButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterDepenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterDepenseButtonActionPerformed
        dialog.addRevenue(pastExpensesModel, upcomingExpensesModel);
    }//GEN-LAST:event_ajouterDepenseButtonActionPerformed

    private void deleteDepenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDepenseButtonActionPerformed
        dialog.deleteRevenue(depensesList.getSelectedIndex(), avenirList.getSelectedIndex(), pastExpensesModel, upcomingExpensesModel);
    }//GEN-LAST:event_deleteDepenseButtonActionPerformed

    private void modifierDepenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierDepenseButtonActionPerformed
        dialog.modifierRevenue(depensesList.getSelectedIndex(), avenirList.getSelectedIndex(), pastExpensesModel, upcomingExpensesModel);
    }//GEN-LAST:event_modifierDepenseButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        financeControl.setVisibleMainView();
    }//GEN-LAST:event_backButtonActionPerformed

    
    public Double getAmountFromString(String element){
        String[] parts = element.split(" - ");
        return Double.parseDouble(parts[2]);
    }
    
    public Double getTotalDepenses(){
        return dialog.getTotalDepenses();
    }
    
    public void setTotalText(double amount){
        totalLabel.setText("Total: " + amount + "€");
    }
        
    public Depense getNewDepenseInput() {
        JTextField descriptionField = new JTextField();
        JTextField amountField = new JTextField();
        JFormattedTextField dateField = createDateField();

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Description:"));
        panel.add(descriptionField);
        panel.add(new JLabel("Montant:"));
        panel.add(amountField);
        panel.add(new JLabel("Date (yyyy-mm-dd):"));
        panel.add(dateField);

        int result = JOptionPane.showConfirmDialog(null, panel, "Votre nouvelle depense:", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            String description = descriptionField.getText();
            double amount = Double.parseDouble(amountField.getText());
            Date date = (Date) dateField.getValue();
            return new Depense(description, date, amount);
        } else {
            return null;
        }
    }
    
    public Depense modifyDepenseInput(Depense existingDepense) {
        JTextField descriptionField = new JTextField(existingDepense.getDescription());
        JTextField amountField = new JTextField(String.valueOf(existingDepense.getAmount()));
        JFormattedTextField dateField = createDateField();
        dateField.setValue(existingDepense.getDate());

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Description:"));
        panel.add(descriptionField);
        panel.add(new JLabel("Montant:"));
        panel.add(amountField);
        panel.add(new JLabel("Date (yyyy-mm-dd):"));
        panel.add(dateField);

        int result = JOptionPane.showConfirmDialog(null, panel, "Modifier Revenue", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            String description = descriptionField.getText();
            double amount = Double.parseDouble(amountField.getText());
            Date date = (Date) dateField.getValue();
            return new Depense(description, date, amount);
        } else {
            return null;
        }
    }

    private JFormattedTextField createDateField() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        JFormattedTextField dateField = new JFormattedTextField(dateFormat);
        dateField.setColumns(10);
        dateField.setValue(new Date());
        return dateField;
    }

    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void showMessage(){
        JOptionPane.showMessageDialog(this, "Veuillez choisir une depense.");
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DepensesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DepensesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DepensesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DepensesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DepensesWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterDepenseButton;
    private javax.swing.JPanel avenirDepensesPanel;
    private javax.swing.JLabel avenirLabel;
    private javax.swing.JList<String> avenirList;
    private javax.swing.JScrollPane avenirScrollPane;
    private javax.swing.JSeparator avenirSeparator;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteDepenseButton;
    private javax.swing.JLabel depensesLabel;
    private javax.swing.JList<String> depensesList;
    private javax.swing.JScrollPane depensesScrollPane;
    private javax.swing.JSeparator depensesSeparator;
    private javax.swing.JButton modifierDepenseButton;
    private javax.swing.JLabel moisLabel;
    private javax.swing.JPanel pastDepensesPanel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables


}
