/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import javax.swing.*;
import control.*;
import utils.MonthSetter;
import java.awt.Color;
/**
 *
 * @author mac
 */
public class FinanceWindow extends JFrame {
    
    private FinanceController control;
    
    /**
     * Creates new form FinanceManager
     */
    public FinanceWindow() {
        initComponents();
        control = new FinanceController(this);
        //updateMonthLabel();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetLabel = new javax.swing.JLabel();
        moisLabel = new javax.swing.JLabel();
        amountMoisLabel = new javax.swing.JLabel();
        amountResteLabel = new javax.swing.JLabel();
        resteLabel = new javax.swing.JLabel();
        revenuesPanel = new javax.swing.JPanel();
        revenusButton = new javax.swing.JButton();
        revenuesLabel = new javax.swing.JLabel();
        amountRevenuesLabel = new javax.swing.JLabel();
        depencesPanel = new javax.swing.JPanel();
        depensesButton = new javax.swing.JButton();
        depencesLabel = new javax.swing.JLabel();
        amountDepencesLabel = new javax.swing.JLabel();
        epargnePanel = new javax.swing.JPanel();
        epargneButton = new javax.swing.JButton();
        epargneLabel = new javax.swing.JLabel();
        amountEpargneLabel = new javax.swing.JLabel();
        budgetSetUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        budgetLabel.setText("Budget mensuel:");

        moisLabel.setFont(new java.awt.Font("Baskerville", 0, 36)); // NOI18N
        moisLabel.setText("Mai");
        moisLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        moisLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        amountMoisLabel.setText("0€ ");

        amountResteLabel.setForeground(new java.awt.Color(204, 0, 0));
        amountResteLabel.setText("0€ ");

        resteLabel.setText("Reste:");

        revenuesPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        revenusButton.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        revenusButton.setText("Voir");
        revenusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenusButtonActionPerformed(evt);
            }
        });

        revenuesLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        revenuesLabel.setText("Revenues");

        amountRevenuesLabel.setText("0.0€ ");

        javax.swing.GroupLayout revenuesPanelLayout = new javax.swing.GroupLayout(revenuesPanel);
        revenuesPanel.setLayout(revenuesPanelLayout);
        revenuesPanelLayout.setHorizontalGroup(
            revenuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revenuesPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(revenuesLabel)
                .addGap(40, 40, 40)
                .addComponent(amountRevenuesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(revenusButton)
                .addGap(40, 40, 40))
        );
        revenuesPanelLayout.setVerticalGroup(
            revenuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenuesPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(revenuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revenusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(revenuesLabel)
                    .addComponent(amountRevenuesLabel))
                .addGap(44, 44, 44))
        );

        depencesPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        depensesButton.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        depensesButton.setText("Voir");
        depensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depensesButtonActionPerformed(evt);
            }
        });

        depencesLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        depencesLabel.setText("Dépenses");

        amountDepencesLabel.setText("0.0€ ");

        javax.swing.GroupLayout depencesPanelLayout = new javax.swing.GroupLayout(depencesPanel);
        depencesPanel.setLayout(depencesPanelLayout);
        depencesPanelLayout.setHorizontalGroup(
            depencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depencesPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(depencesLabel)
                .addGap(40, 40, 40)
                .addComponent(amountDepencesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(depensesButton)
                .addGap(39, 39, 39))
        );
        depencesPanelLayout.setVerticalGroup(
            depencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depencesPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(depencesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depensesButton)
                    .addComponent(depencesLabel)
                    .addComponent(amountDepencesLabel))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        epargnePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        epargneButton.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        epargneButton.setText("Voir");
        epargneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epargneButtonActionPerformed(evt);
            }
        });

        epargneLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        epargneLabel.setText("Épargne");

        amountEpargneLabel.setText("0.0€ ");

        javax.swing.GroupLayout epargnePanelLayout = new javax.swing.GroupLayout(epargnePanel);
        epargnePanel.setLayout(epargnePanelLayout);
        epargnePanelLayout.setHorizontalGroup(
            epargnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, epargnePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(epargneLabel)
                .addGap(47, 47, 47)
                .addComponent(amountEpargneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(epargneButton)
                .addGap(39, 39, 39))
        );
        epargnePanelLayout.setVerticalGroup(
            epargnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epargnePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(epargnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epargneButton)
                    .addComponent(epargneLabel)
                    .addComponent(amountEpargneLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        budgetSetUpButton.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        budgetSetUpButton.setText("Set up");
        budgetSetUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetSetUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(revenuesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depencesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(epargnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(budgetLabel)
                            .addComponent(resteLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amountMoisLabel)
                            .addComponent(amountResteLabel)))
                    .addComponent(moisLabel))
                .addGap(18, 18, 18)
                .addComponent(budgetSetUpButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(moisLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(budgetLabel)
                            .addComponent(amountMoisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountResteLabel)
                            .addComponent(resteLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(budgetSetUpButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(revenuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(depencesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(epargnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depensesButtonActionPerformed
        control.showExpensesWindow();
    }//GEN-LAST:event_depensesButtonActionPerformed

    private void revenusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenusButtonActionPerformed
        control.showRevenuesWindow();
    }//GEN-LAST:event_revenusButtonActionPerformed

    private void epargneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epargneButtonActionPerformed
        control.showSavingsWindow();
    }//GEN-LAST:event_epargneButtonActionPerformed

    private void budgetSetUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetSetUpButtonActionPerformed
        String newBudgetStr = JOptionPane.showInputDialog(this, "Entrez le nouveau budget:");
        if (newBudgetStr != null && !newBudgetStr.isEmpty()) {
            double newBudget = Double.parseDouble(newBudgetStr);
            amountMoisLabel.setText(newBudget + "€");
        }
        control.updateMainView();
        budgetSetUpButton.setEnabled(false);
        updateMonthLabel();
    }//GEN-LAST:event_budgetSetUpButtonActionPerformed
    
    public double getBudget() {
        String text = amountMoisLabel.getText();
        String numberText = text.replace("€", "").trim();
        try {
            return Double.parseDouble(numberText);
        } catch (NumberFormatException e) {
            e.printStackTrace();
            return 0.0;
        }
    }
    
    /**
     *
     * @param budget
     * @param depenses
     * @param revenues
     * @param savings
     */
    public void updateBudgetInfo(double budget, double depenses, double revenues, double savings) {
        double reste = budget - depenses;
        updateReste(reste);
        amountResteLabel.setText(reste + "€");
        amountMoisLabel.setText(budget+ "€");
        amountDepencesLabel.setText(depenses + "€");
        amountRevenuesLabel.setText(revenues + "€");
        amountEpargneLabel.setText(savings + "€");
    }
    
    public void updateReste(double rest){
        if (rest<=0){
            amountResteLabel.setForeground(new Color(204, 0, 0));
        } else {
            amountResteLabel.setForeground(new Color(0, 153, 51));
        }
        amountResteLabel.setText(String.format("%.1f€", rest));
    }
    
    private void updateMonthLabel() {
        moisLabel.setText(MonthSetter.getCurrentMonth());
    }
    
    public String getMonthLabel(){
        return moisLabel.getName();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FinanceWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountDepencesLabel;
    private javax.swing.JLabel amountEpargneLabel;
    private javax.swing.JLabel amountMoisLabel;
    private javax.swing.JLabel amountResteLabel;
    private javax.swing.JLabel amountRevenuesLabel;
    private javax.swing.JLabel budgetLabel;
    private javax.swing.JButton budgetSetUpButton;
    private javax.swing.JLabel depencesLabel;
    private javax.swing.JPanel depencesPanel;
    private javax.swing.JButton depensesButton;
    private javax.swing.JButton epargneButton;
    private javax.swing.JLabel epargneLabel;
    private javax.swing.JPanel epargnePanel;
    private javax.swing.JLabel moisLabel;
    private javax.swing.JLabel resteLabel;
    private javax.swing.JLabel revenuesLabel;
    private javax.swing.JPanel revenuesPanel;
    private javax.swing.JButton revenusButton;
    // End of variables declaration//GEN-END:variables
}
