/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import dialog.DialogRevenuesWindow;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Budget;
import model.Depense;
import control.*;

/**
 *
 * @author mac
 */
public class RevenuesWindow extends JFrame {
    
    private DialogRevenuesWindow dialog;
    private FinanceController financeControl;
    private DefaultListModel<String> pastRevenuesModel;
    private DefaultListModel<String> avenirRevenuesModel;

    /**
     * Creates new form RevenuesWindow
     */
    public RevenuesWindow(FinanceController financeControl) {
        this.financeControl = financeControl;
        initComponents();
        
        dialog = new DialogRevenuesWindow(this);
        
        pastRevenuesModel = new DefaultListModel<String>();
        avenirRevenuesModel = new DefaultListModel<String>();
        
        revenuesList.setModel(pastRevenuesModel);
        avenirRevenuesList.setModel(avenirRevenuesModel);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setDialogue(DialogRevenuesWindow dialog) {
        this.dialog = dialog;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountLabel = new javax.swing.JLabel();
        moisLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        revenuesLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        revenuesList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        avenirLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        avenirRevenuesList = new javax.swing.JList<>();
        revenueModifierButton = new javax.swing.JButton();
        revenueDeleteButton = new javax.swing.JButton();
        revenueAjouterButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        amountLabel.setFont(new java.awt.Font("Heiti TC", 0, 18)); // NOI18N
        amountLabel.setText("total: 500€");

        moisLabel.setFont(new java.awt.Font("Baskerville", 0, 36)); // NOI18N
        moisLabel.setText("Mois");
        moisLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        moisLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        revenuesLabel.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        revenuesLabel.setText("Revenues");

        jScrollPane1.setViewportView(revenuesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(revenuesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(revenuesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        avenirLabel.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        avenirLabel.setText("A venir");

        avenirRevenuesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(avenirRevenuesList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(avenirLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avenirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        revenueModifierButton.setText("Modifier");
        revenueModifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueModifierButtonActionPerformed(evt);
            }
        });

        revenueDeleteButton.setText("-");
        revenueDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueDeleteButtonActionPerformed(evt);
            }
        });

        revenueAjouterButton.setText("+");
        revenueAjouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueAjouterButtonActionPerformed(evt);
            }
        });

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(amountLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backButton)
                                        .addGap(147, 147, 147)
                                        .addComponent(moisLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(revenueModifierButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(revenueDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(revenueAjouterButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moisLabel)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(amountLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revenueAjouterButton)
                    .addComponent(revenueDeleteButton)
                    .addComponent(revenueModifierButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revenueModifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueModifierButtonActionPerformed
        dialog.modifierRevenue(revenuesList.getSelectedIndex(), avenirRevenuesList.getSelectedIndex(), 
                pastRevenuesModel, avenirRevenuesModel);
    }//GEN-LAST:event_revenueModifierButtonActionPerformed

    private void revenueDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueDeleteButtonActionPerformed
        dialog.deleteRevenue(revenuesList.getSelectedIndex(), avenirRevenuesList.getSelectedIndex(), 
                pastRevenuesModel, avenirRevenuesModel);
    }//GEN-LAST:event_revenueDeleteButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dialog.back();
        financeControl.setVisibleMainView();
    }//GEN-LAST:event_backButtonActionPerformed

    private void revenueAjouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueAjouterButtonActionPerformed
        dialog.addRevenue(pastRevenuesModel, avenirRevenuesModel);
    }//GEN-LAST:event_revenueAjouterButtonActionPerformed

    public void showMessage(){
        JOptionPane.showMessageDialog(this, "Veuillez choisir une revenue.");
    }
    
    public void setTotalText(double amount){
        amountLabel.setText("Total: " + amount + "€");
    }
    
    public double getTotalRevenues(){
        return dialog.getTotalRevenues();
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RevenuesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RevenuesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RevenuesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RevenuesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RevenuesWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel avenirLabel;
    private javax.swing.JList<String> avenirRevenuesList;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel moisLabel;
    private javax.swing.JButton revenueAjouterButton;
    private javax.swing.JButton revenueDeleteButton;
    private javax.swing.JButton revenueModifierButton;
    private javax.swing.JLabel revenuesLabel;
    private javax.swing.JList<String> revenuesList;
    // End of variables declaration//GEN-END:variables

    
    public Depense getNewRevenueInput() {
        JTextField descriptionField = new JTextField();
        JTextField amountField = new JTextField();
        JFormattedTextField dateField = createDateField();

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Description:"));
        panel.add(descriptionField);
        panel.add(new JLabel("Montant:"));
        panel.add(amountField);
        panel.add(new JLabel("Date (yyyy-MM-dd):"));
        panel.add(dateField);

        int result = JOptionPane.showConfirmDialog(null, panel, "Votre nouvelle revenue", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            String description = descriptionField.getText();
            double amount = Double.parseDouble(amountField.getText());
            Date date = (Date) dateField.getValue();
            return new Depense(description, date, amount);
        } else {
            return null;
        }
    }
    
    public Depense modifyRevenueInput(Depense existingDepense) {
        JTextField descriptionField = new JTextField(existingDepense.getDescription());
        JTextField amountField = new JTextField(String.valueOf(existingDepense.getAmount()));
        JFormattedTextField dateField = createDateField();
        dateField.setValue(existingDepense.getDate());

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Description:"));
        panel.add(descriptionField);
        panel.add(new JLabel("Montant:"));
        panel.add(amountField);
        panel.add(new JLabel("Date (yyyy-mm-dd):"));
        panel.add(dateField);

        int result = JOptionPane.showConfirmDialog(null, panel, "Modifier Revenue", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            String description = descriptionField.getText();
            double amount = Double.parseDouble(amountField.getText());
            Date date = (Date) dateField.getValue();
            return new Depense(description, date, amount);
        } else {
            return null;
        }
    }


    private JFormattedTextField createDateField() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        JFormattedTextField dateField = new JFormattedTextField(dateFormat);
        dateField.setColumns(10);
        dateField.setValue(new Date());
        return dateField;
    }
}
